---
services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: false
  extensionConfiguration.vd_webservice:
    arguments:
      - vd_webservice
    class: array
    factory:
      - '@TYPO3\CMS\Core\Configuration\ExtensionConfiguration'
      - get
  Vd\VdWebservice\:
    resource: ../Classes/*
  Vd\VdWebservice\Middleware\ApiMiddleware:
    arguments:
      $extensionConfiguration: '@extensionConfiguration.vd_webservice'
