---
services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: false
  extensionConfiguration.vd_core.environmentPath:
    arguments:
      - vd_core
      - environmentPath
    class: string
    factory:
      - '@TYPO3\CMS\Core\Configuration\ExtensionConfiguration'
      - get
  Vd\VdCore\:
    resource: ../Classes/*
  Vd\VdCore\Command\EnvironmentDataCommand:
    arguments:
      $environmentPath: '@extensionConfiguration.vd_core.environmentPath'
    tags:
      -
        command: vd_core:environment_data
        description: Add environment data for the current version.
        name: console.command
  Vd\VdCore\Command\GenerateHtaccessCommand:
    tags:
      -
        command: install:generatehtaccess
        description: Generate .htaccess file and replace marker with environment variables
        name: console.command
        schedulable: false
  Vd\VdCore\Command\GenerateLocalConfigurationCommand:
    tags:
      -
        command: install:generatelocalconfiguration
        description: Generate LocalConfiguration.php file
        name: console.command
        schedulable: false
  Vd\VdCore\Resolver\ContentSecurityPolicyResolver:
    arguments:
      $cache: '@cache.core'
  Vd\VdCore\SystemInformation\ToolbarItemProvider:
    arguments:
      $environmentPath: '@extensionConfiguration.vd_core.environmentPath'
    tags:
      -
        identifier: vd-core/show-dgnsi-version
        name: event.listener
