---
services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: false
  Vd\VdSmallAds\:
    resource: ../Classes/*
  Vd\VdSmallAds\Command\ImportCommand:
    tags:
      -
        command: vdsmallads:import
        description: Imports small ads via a webservice.
        name: console.command
