CREATE TABLE `tx_vdwsprosecutor_domain_model_officehour` (
	`api_response` text COLLATE utf8mb4_unicode_ci NOT NULL,
	`end_shift` int(10) UNSIGNED NOT NULL DEFAULT 0,
	`end_shift_date` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
	`end_shift_date_hour` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
	`end_shift_day` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
	`end_shift_hour` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
	`event` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
	`external_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
	`magistrate_first_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
	`magistrate_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
	`magistrate_last_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
	`magistrate_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
	`modification_date` int(10) UNSIGNED NOT NULL DEFAULT 0,
	`office` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
	`start_shift` int(10) UNSIGNED NOT NULL DEFAULT 0,
	`start_shift_date` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
	`start_shift_date_hour` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
	`start_shift_day` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
	`start_shift_hour` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
	`substitute_first_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
	`substitute_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
	`substitute_last_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
	`substitute_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT ''
);
